### ISSUE TITLE
[BUG] No event validation for training and validation epoch handling in visdom plot

### ISSUE THREAD

**Issue by banctilrobitaille** [banctilrobitaille/kerosene#37]
**Describe the bug**
The same function is used to validate the training and validation in an if else if manner. If the shouldHandleStep function is false for training it could be true for validation even if the fired event is training. This leads to unwanted ploting.

**Comment by pldelisle** [comment]
See [PR#39](https://github.com/banctilrobitaille/kerosene/pull/39).
