### ISSUE TITLE
[FEATURE] Implement Dataparallel support

### ISSUE THREAD

**Issue by banctilrobitaille** [banctilrobitaille/kerosene#46]
**Is your feature request related to a problem? Please describe.**
Yes, the application is not working when user has multiple GPU and launching without the torch launcher.

**Comment by pldelisle** [comment]
We won't add this feature. We implemented with the toughest and most commonly used parallel way of training a model in Pytorch using `torch.nn.distributed.DistributedDataParallel`. 

From Pytorch docs:

> DataParallel is single-process, multi-thread, and only works on a single machine, while DistributedDataParallel is multi-process and works for both single- and multi- machine training. Thus, even for single machine training, where your data is small enough to fit on a single machine, DistributedDataParallel is expected to be faster than DataParallel. DistributedDataParallel also replicates models upfront instead of on each iteration and gets Global Interpreter Lock out of the way.
If both your data is too large to fit on one machine and your model is too large to fit on a single GPU, you can combine model parallel (splitting a single model across multiple GPUs) with DistributedDataParallel. Under this regime, each DistributedDataParallel process could use model parallel, and all processes collectively would use data parallel.

Going the Distributed way is the best to go. No need to implement another one.
